FROM kolla/centos-source-base:9.0.1
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="tripleoclient" build-date="20200121"








RUN echo 'tripleoclient not yet available for centos source installs' && /bin/false



COPY create_super_user.sh /usr/local/bin/create_super_user.sh
RUN chmod 750 /usr/local/bin/create_super_user.sh


