FROM kolla/centos-source-sahara-base:9.0.1
LABEL maintainer="Kolla Project (https://launchpad.net/kolla)" name="sahara-engine" build-date="20200121"






    
       
    


RUN yum -y install nc \
    && yum clean all && rm -rf /var/cache/yum




USER sahara